# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('es_primary_pt_gp', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pim', models.IntegerField()),
                ('es_gf_rel', models.DecimalField(decimal_places=4, max_digits=20)),
                ('es_ga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
